- hosts: all  
  become: yes  
  vars:
    ansible_become_password: "{{ vault_pass }}"
  tasks:
    - name: Enable repo
      command: amazon-linux-extras enable nginx1

    - name: Install nginx
      package:
        name: nginx
        state: present
