- hosts: all  
  become: yes  
  vars:
    ansible_become_password: "{{ vault_pass }}"
  tasks:
    - name: Enable repo
      command: amazon-linux-extras enable nginx1

    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started 

    - name: Create sites-available & sites-enabled directory
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0644
      loop:
        - /etc/nginx/sites-available/default
        - /etc/nginx/sites-enabled/default

    - name: Copy nginx file
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default

    - name: Enable config
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Copy index file
      copy:
        src: index.html
        dest: /usr/share/nginx/html

    - name: Restart nginx
      service:
        name: nginx
        state: restarted  
